# Generated by Django 5.2.4 on 2025-08-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_issues', 'Can view issues'), ('view_report', 'Can view report'), ('add_issue', 'Can add issue'), ('change_issue', 'Can change issue'), ('delete_issue', 'Can delete issue')],
            },
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_issues', 'Can view issues'), ('view_report', 'Can view report'), ('add_issue', 'Can add issue'), ('change_issue', 'Can change issue')],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_issues', 'Can view issues'), ('view_report', 'Can view report')],
            },
        ),
    ]
